version: '3.8'

services:
  api:
    build: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend_app_network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: document_manager
    ports:
      - "5432:5432"
    networks:
      - backend_app_network

networks:
  backend_app_network:
    driver: bridge
