"""Add parsed_text to Document

Revision ID: f1c390423ff1
Revises: 
Create Date: 2024-12-27 12:33:11.893172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c390423ff1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_text', sa.Text(), nullable=True))
    op.alter_column('documents', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=True,
                    postgresql_using='created_at::timestamp without time zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'parsed_text')
    # ### end Alembic commands ###
